project:
  type: website
  output-dir: docs
  # resources: 
  #   - assets/js/fix-accessibility.js

website:
  title: "LANDFIRE in Fire Needs Assessments"
  page-navigation: true
  # google-analytics: G-7HYRRL98N6
  sidebar: 
    - id: main
      style: "docked"
      search: true
      contents:
        - text: "Fire Needs Assessments: A landscape management tool"
          href: index.qmd
        - text: "An introduction to Fire Needs Assessments"
          href: intro-to-fna.qmd
        - text: "How can LANDFIRE help?"
          href: landfire-overview.qmd
        - section: "Fire Needs Assessments Datasets"
          href: bps.qmd
          contents:
            - href: bps.qmd
            - href: evt.qmd
            - href: fire-regimes.qmd
        - text: "An overview of the FNA Process"
          href: fna-overview.qmd
          
    - id: ArcGIS-sidebar
      style: "docked"
      search: true
      contents:     
        - section: "The Fire Needs Assessment Process"
          href: ArcGIS/historical-vegetation.qmd
          contents:
          - section: Processing your data
            contents:
              - href: ArcGIS/historical-vegetation.qmd
              - href: ArcGIS/current-vegetation.qmd
              - href: ArcGIS/mask-bps.qmd
              - href: ArcGIS/combine-and-join.qmd
              - href: ArcGIS/export-to-csv.qmd
          - section: Analyzing your data
            contents:
              - href: ArcGIS/tabular-csv.qmd
              - href: ArcGIS/tabular-evt-acres.qmd
              - href: ArcGIS/tabular-pivot-table.qmd
              - href: ArcGIS/tabular-weighted-average.qmd
              - href: ArcGIS/tabular-summary-table.qmd
              - href: ArcGIS/tabular-import-csv.qmd
          - text: "Next Steps"
            href: next-steps.qmd
    
    - id: r-workflow-sidebar
      style: "docked"
      search: true
      contents:
        - text: "An introduction to using R for Fire Needs Assessments"
          href: r-workflow/r-introduction.qmd
        - text: "R setup and packages"
          href: r-workflow/r-setup.qmd
        - text: "Download LANDFIRE data"
          href: r-workflow/r-download.qmd
        - section: "The Fire Needs Assessment Process"
          href: r-workflow/r-mask-rasters.qmd
          contents:
           - href: r-workflow/r-mask-rasters.qmd
           - href: r-workflow/r-combine.qmd
           - href: r-workflow/r-tabular.qmd
        - text: "Next Steps"
          href: next-steps.qmd

    
  navbar:
    left:
      - text: "An Overview of Fire Needs Assessments"
        href: index.qmd
      - text: "Fire Needs Assessments in ArcGIS Pro"
        href: ArcGIS/historical-vegetation.qmd
      - text: "Fire Needs Assessments in R"
        href: r-workflow/r-introduction.qmd

    
  body-footer: |
    # Still have questions? LANDFIRE is here to help.

    -   Ask the [LANDFIRE Helpdesk](mailto:helpdesk@landfire.gov?subject=landfirehelp) (email link).

    -   Search and subscribe to the [LANDFIRE YouTube Channel](https://www.youtube.com/@LANDFIREvideo) (see tutorials, Office Hours, quick demonstrations).

    -   [Join an Office Hour](https://tnc.zoom.us/meeting/register/tJArf-igqD8oE9S7qGDsOm7oeF7aZBJDMqBG#/registration) (monthly meeting with open format Q & A with LANDFIRE experts).

    -   [Schedule a meeting](mailto:landfire@tnc.org?subject=landfirehelp) (email link) with TNCâ€™s LANDFIRE Team.
    
    
    # navbar:

format:
  html:
    theme: 
      light: [lumen, styles-light.scss]
      dark: [cyborg, styles-dark.scss]
    respect-user-color-scheme: true 
    # include-after-body:
    #   text: |
    #     <script type="application/javascript" src="/assets/js/fix-accessibility.js"></script>
    toc: false
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 2.25rem

editor: source


